### ISSUE TITLE
Fixed material-tab height

### ISSUE THREAD

**Issue by ltackmann** [dart-lang/angular_components#12]
It would be great to get the ability to control a material tabs height. Making it take up the remaining height in the material-tab-panel.

**Comment by nshahan** [comment]
Can you explain this a little more? Are you looking for a way to ensure that all the tabs in a panel occupy the same amount of space vertically?

**Comment by ltackmann** [comment]
Yes, I want to be able to set the hight of the entire material-tab-panel and then have the tabs themself occupy the remaining space inside the panel vertically. Similar to how you with flexbox can force a container to fill out vertically

**Comment by nshahan** [comment]
I think the tabs are designed as a central content navigation feature so there wasn't the expectation that there would be content bouncing up and down below the tabs as you select different tabs.
https://material.google.com/patterns/navigation.html#navigation-patterns 

@TedSander Any thoughts on all the tab panels having the same size?

**Comment by matanlurey** [comment]
So the actual material design specification I believe does not support this.

Let's wait for @TedSander to get back from vacation and ask again.

**Comment by TedSander** [comment]
Good news is that you can already do this yourself. Here is some example CSS to get it working:

```css
.tab-panel {
  width: 400px;
  height: 400px;
  display: flex;
  flex-direction: column;
}

/*This is a class that is applied to the currently selected tab content*/
.material-tab {
  flex: 1;
}
```

I haven't thought through if we can have this as the default. It may make sense, but I'm not sure who it might break. For now it is easy enough for anyone to do.
