### ISSUE TITLE
Material Button Type

### ISSUE THREAD

**Issue by arcas0803** [dart-lang/angular_components#132]
No way to use a material button like a submit button with the ng-form api on angular 4. The type is not working.
` <form #Form = "ngForm" (ngSubmit)="onSubmit(Form.value)">
   <material-button raised type = "submit" >Enviar
            </material-button>
`
The trigger option can not work as it should with the ng-form.

**Comment by TedSander** [comment]
material-button isn't actually backed by an html button. It is a div underneath. So it is infeasible to have it by a type="submit". That said it is pretty easy to allow a material-button to submit a form:

`<form #form = "ngForm"> <material-button raised (trigger) = "form.onSubmit(null)" >Enviar </material-button>`

Or since you are already calling on submit:

`<form #form = "ngForm"> <material-button raised (trigger) = "onSubmit(form.value)" >Enviar </material-button>`

**Comment by chances** [comment]
The lack of this breaks a form's accessibility. With @TedSander's suggestion a form has no explicitly declared submit button and cannot be submitted with the Enter key when a form control is focused.

In order to preserve expected behavior for forms I have to wrap a `material-button` in a HTML `button type="submit"` and add some hacky CSS to keep the material button presentable.

```html
<button type="submit">
    <material-button (trigger)="form.onSubmit($event)">Submit</material-button>
</button>
```

```css
button {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    border: 0;
    padding: 0;
    font-size: inherit;
    background: transparent;
  }
```

This is pretty backwards given it is already a button component. `material-button` should be fixed by baking it with a HTML `button`.
