### ISSUE TITLE
App Layout component scrolling content border

### ISSUE THREAD

**Issue by imtusharrai** [dart-lang/angular_components#162]
I am applying app layout component of angular components with angular dart project, but while adding a scrollable content in `material-content` the border disappears. Have a look at the images attached.
![untitled](https://user-images.githubusercontent.com/14331677/30700617-ad38204e-9f05-11e7-83c6-f6494a51071a.png)

**Comment by SCKelemen** [comment]
@tusharrai2 I'm having trouble figuring out how to use App Layout, would you mind sharing an example?

**Comment by tusharrai2** [comment]
Hi Samuel,

It's easy to use Application Layout component with Angular Dart. Simply
create a folder naming your component in the *project/lib of html,scss and
dart* file of the component and place the example content in those files.

Thanks

Revert if having any confusion.


On Oct 20, 2017 9:47 PM, "Samuel Kelemen" <notifications@github.com> wrote:

@tusharrai2 <https://github.com/tusharrai2> I'm having trouble figuring out
how to use App Layout, would you mind sharing an example?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dart-lang/angular_components/issues/162#issuecomment-338253325>,
or mute the thread

**Comment by cedx** [comment]
@imtusharrai A solution could be to make the `material-content` component an absolute positioned element with automatic overflow.

In your application/root component's stylesheet:

```scss
$mat-header-height: 64px;

.material-header + material-drawer + material-content {
  min-height: auto;
}

.material-header {
  z-index: 1;

  .material-header-row {
    height: $mat-header-height;
  }
}

material-content {
  bottom: 0;
  left: 0;
  overflow: auto;
  position: absolute;
  right: 0;
  top: $mat-header-height;
}
```
