### ISSUE TITLE
app layout drawer can't be in an angular component

### ISSUE THREAD

**Issue by Kleak** [dart-lang/angular_components#181]
a screenshot of a 'normal' use of the app layout as in the example
![screenshot from 2017-10-20 23-08-13](https://user-images.githubusercontent.com/5434752/31841847-987b75f0-b5eb-11e7-9143-744620cadd92.png)
and the code that produce it
```dart
<material-drawer persistent #drawer="drawer">

  <material-list>
    <div group class="mat-drawer-spacer"></div>

    <div group>
      ...
    </div>
    
    ...
  </material-list>
</material-drawer>

<material-content>
  <header class="material-header shadow">
    <div class="material-header-row">
      <material-button icon
                       class="material-drawer-button" (trigger)="drawer.toggle()">
        <material-icon icon="menu"></material-icon>
      </material-button>
      <span class="material-header-title">{{title}}</span>
      <div class="material-spacer"></div>
    </div>
  </header>

  <router-outlet></router-outlet>

</material-content>
```

and now the problem i would like to put the list inside the drawer into an other component so here is the code :

```dart
<material-drawer persistent #drawer="drawer">

  <my-drawer></my-drawer>

</material-drawer>

<material-content>
  <header class="material-header shadow">
    <div class="material-header-row">
      <material-button icon
                       class="material-drawer-button" (trigger)="drawer.toggle()">
        <material-icon icon="menu"></material-icon>
      </material-button>
      <span class="material-header-title">{{title}}</span>
      <div class="material-spacer"></div>
    </div>
  </header>

  <router-outlet></router-outlet>

</material-content>
```

and the html of `my-drawer`
```dart
<material-list>
  <div group class="mat-drawer-spacer"></div>

  <div group>
    <material-list-item>
      <material-icon icon="assignment"></material-icon>Form name
    </material-list-item>
  </div>

  <div group>
    <material-list-item (trigger)="logout()">
      <material-icon icon="exit_to_app"></material-icon>Sign out
    </material-list-item>
  </div>
</material-list>
```

and the screenshot 
![screenshot from 2017-10-20 23-20-16](https://user-images.githubusercontent.com/5434752/31842215-44671d0a-b5ed-11e7-88e8-20f9451584f3.png)

as you can see the icon doesn't have the same color and also the list take less place.

**Comment by TedSander** [comment]
So layout.scss has some CSS rules inside of it to make the material-list items look nicer. Here: https://github.com/dart-lang/angular_components/blob/acadfd779b71230d2a5c1adb538e7b74182da881/lib/app_layout/layout.scss#L235

Since you are wrapping the list-items in a component you are adding style encapsulation so it can't use those rules directly.

I've exposed a mixin that will be available in the next release but until then you could copy the styles into the CSS of your component.

**Comment by TedSander** [comment]
@nshahan can you close when this change get's pushed externally? CL landed internally.

**Comment by nshahan** [comment]
The version that supports angular: 5.0.0-alpha has been published. It includes the updates to the mixins. https://pub.dartlang.org/packages/angular_components/versions/0.9.0-alpha

**Comment by Kleak** [comment]
0.9.0-alpha support angular 4 ?
if no it is possible to publish it also in 0.8.x version ?

**Comment by nshahan** [comment]
Angular 5.0.0-alpha only changes have already landed in the angular_components. In my experience apps wont build with angular 4.0.0 without identifying and reverting some changes. I don't expect to release any more versions on the 0.8.x branch unless there is a dire need to cherry pick changes to merge in.

**Comment by TedSander** [comment]
@Kleak you can patch it locally yourself by putting the result of the [mixin](https://github.com/dart-lang/angular_components/blob/d700a88143ed3a177271c3a356f19fbcdef0d7fd/lib/app_layout/_mixins.scss#L33) into your component scss directly like so:

```scss
:host {
  material-list {
    // Remove the padding on the default list component when it is used in the
    // drawer.
    padding: 0;
  }

  // Use the label attribute from material-list but ensure the style is right
  // for the drawer.
  [label] {
    @include list-item-base;
    align-items: center;
    // TODO(google) Remove once material-list uses the right color value.
    color: $mat-light-transparent-black;
    display: flex;
  }

  material-list-item,
  [label] {
    font-weight: $mat-font-weight-medium;
    // The default size/padding for list item is incorrect for the drawer spec.
    height: $mat-grid * 6;
    padding: 0 $mat-grid * 2;

    material-icon {
      color: $mat-light-transparent-black;
      margin-right: $mat-grid * 4;
    }
}
```
