### ISSUE TITLE
Problem with pre-compilation of angular_components: 0.8.0

### ISSUE THREAD

**Issue by rwrozelle** [dart-lang/angular_components#233]
I'm having a problem with pre-compilation of angular_components: 0.8.0, My project would compile in January, been away for a while and picked back up.   
Able to duplicate this problem using the AngularDart Web App - a web app with material design components template in IDEA community.  Below is the pubspec from template and error message.
I'm not ready to move to bleeding edge, on current stable release of Dart.

```
name: testdart
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: development <email@example.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- angular:
    entry_points:
      - web/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
```
Error message during get:
```
Precompiling dependencies...
Loading source assets...
Loading angular, sass_builder and dart_to_js_script_rewriter transformers...
Error on line 26, column 5 of ../../.pub-cache/hosted/pub.dartlang.org/angular_components-0.8.0/pubspec.yaml: Error loading transformer: 'package:sass_builder/sass_builder.dart': malformed type: line 34 pos 20: cannot resolve class 'Logger' from 'SassBuilder'
  final _log = new Logger('sass_builder');
```
