### ISSUE TITLE
Components become laggy

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular_components#250]
After numerous components have been routed to and destroyed I am noticing that the angular_components become laggy. Some of the issues I've seen are:

- Tab triggers are delayed
- Tabs animation sometimes gets stuck half way through selecting another tab
- Material list triggers become delayed
- Material list item triggers on incorrect item
- Sometimes multiple taps are required to get an angular_component to trigger

This tends to only happen after a couple of minutes of using my app which suggests possibly a memory leak? (I'm aware I may have introduced this somehow). What's strange is the rest of the app remains fast, it's just the components become laggy.

You can see a screen recording here showing some of the issues listed above:
https://photos.app.goo.gl/UMjRFWybMRMTm8Kr2

I have a much more complex angular dart 4 app that doesn't experience the same issues. 

I can provide a link to see the web app if this would help.

**Comment by nshahan** [comment]
What versions of angular, angular_components, and the Dart SDK are you using?

Was that app built with dart2js or the dart-dev-compiler?

**Comment by jimmyff** [comment]
DDC, build runner and the latest versions of all the packages (as of 2 days ago). I'm away from laptop at the moment but will follow up with specific versions.

**Comment by jimmyff** [comment]
Hey @nshahan details below:

- angular: "5.0.0-alpha+10"
- angular_components: "0.9.0-alpha+10"
- Dart: 2.0.0-dev.47.0
- built with DDC

**Comment by nshahan** [comment]
Are you running this on a mobile device or a simulator with limited RAM? Have you tried a build with dart2js? The build with DDC is a debug build and expected to be much larger than a release build with dart2js. I have seen this cause memory issues in some instances when using the dev build in a environment with limited resources.

What compiler are you using for the build in the angular v4.x.x app?
I'd also recommend doing some memory profiling with chrome dev tools to see if you can pinpoint a leak and where it is coming from.

**Comment by jimmyff** [comment]
Oh apologies, I'm using dart2js for the build, forgot that i setup the `build.release.yaml` file: 
 
```
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
          - web/sw.dart
        options:
          compiler: dart2js
          dart2js_args:
            - --fast-startup
            - --minify
            - --trust-type-annotations
            - --trust-primitives
```
The capture is from a mobile device (Pixel 1). The Angular 4 app is built using `pub build` (dart2js)

I'll see if I can see anything with the chrome dev tools.
