### ISSUE TITLE
Dark theme not fully implemented

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular_components#253]
I've been trying to wrap my head around how the Dark Theme works but it doesn't seem like it's been finished, is this work in progress? 

The `[darkTheme]` directive and `AcxDarkTheme` in `lib/theme/` work however the mixin `@mixin acx-theme-dark()` is only utilised by `material-button` and `material-tooltip`. (The example in the comments in the `dark_theme.dart` is not valid code). The `material-button` uses this mixin however it always set the button  to blue if you use the dark theme (despite the fact I had set material-theme to a green): 

```scss
@mixin _button-raised {
  @include material-shadow;

  @include acx-theme-dark {
    background-color: $mat-blue;
  }

  &[disabled] {
    background: $button-disabled-background;
    @include shadow-none;

    @include acx-theme-dark {
      background: $button-disabled-background-dark;
    }
  }
}
```

 - The rest of the components need dark theme support adding
 - The documentation needs correcting
 - The current implementation in material-button needs fixing
 - Perhaps an example of how to use the AcxDarkTheme class and directive would be nice too
 - What does Acx stand for? could this be dropped?
