### ISSUE TITLE
material-input-unfocused-underline-color mixin not working correctly

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular_components#254]
Using the following mixin:
```scss
@include material-input-unfocused-underline-color(hotpink);
```
gets over-ruled by `background: $mat-border-light;` in `material_input.scss`: 
```scss
.unfocused-underline {
  height: 1px;
  background: $mat-border-light;
  border-bottom-color: $mat-border-light;
  position: relative;
  top: -1px;
}
```
