### ISSUE TITLE
webstorm unkonw tag material-*

### ISSUE THREAD

**Issue by bunnyfish** [dart-lang/angular_components#287]
WebStorm 2018.1.5
Build #WS-181.5281.31, built on June 14, 2018

![image](https://user-images.githubusercontent.com/37355378/42310529-3c239c1c-806e-11e8-83b7-b70996c67c97.png)

```
environment:
  sdk: '>=2.0.0-dev.66.0 <2.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta

dev_dependencies:
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0

```
webstorm  don't known material-* tag, how to   fix it,thanks
