### ISSUE TITLE
material-button unresponsive on iOS

### ISSUE THREAD

**Issue by afpatmin** [dart-lang/angular_components#335]
Material-button has to be tapped twice before a trigger event is fired. 

Device: iPhone X
Browser: Safari

**Comment by nshahan** [comment]
I don't see this problem on iOS. Do you have a reproduction?

**Comment by afpatmin** [comment]
I spoke too soon, the issue was I was using changeDetection.OnPush on an ancestor, closing

**Comment by muzuro** [comment]
I am facing same problem, I need to tap twice to call trigger on `material-button` . First click fire "hover" css change and only second fire "trigger" handler.
I have versions:
```
  angular: ^5.1.0
  angular_components: ^0.10.0
```
iOS version: 11.3.1 (15E302)
AppleWebKit: 605.1.15 Safari: 604.1

**Comment by jimmyff** [comment]
The issue is with the hover state - `material-button`, `tab-button` and `material-fab` all add an `::after` on `:hover` state. setting it's `display: none` fixes the issue.

This is my workaround:

```scss
::ng-deep material-button, ::ng-deep tab-button, ::ng-deep material-fab {
  &:after {
    display:none !important;
  }
}
```
