### ISSUE TITLE
Demonstrate how to use SASS to customize the layout

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_components#374]
I think it would be quite helpful to have at least some entry-level example how to apply custom styles mentioned in https://github.com/dart-lang/angular_components#custom-component-styles

**Comment by treyerl** [comment]
SASS Mixins don't work for me, unfortunately.

1. I create a project using `stagehand web-angular`
2. I try to run `webdev serve` and have to update and add a few dependencies to make it work. Currently my pubspec.yaml looks like:

```
environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.13.0

dev_dependencies:
  sass_builder: ^2.1.3
  angular_test: ^2.2.0
  build_runner: ^1.7.0
  build_test: ^0.10.3
  build_web_compilers: ^2.0.0
  build_daemon: ^2.1.0
  pedantic: ^1.0.0
  test: ^1.5.1
```

3. I open `lib/app_components.css` and add the line:
`@import 'package:angular_components/css/material/material';`

4. webdev serve fails with 

```
[SEVERE]build_web_compilers:entrypoint on web/main.dart: Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:angular_components/css/material/material.shim.dart' as import0;` from test_ang_dart_sass|lib/app_component.css.shim.dart at 1:1
```

5. searching the internet, but not finding anything. I also tried to add a build.yaml containing
```
targets:
  $default:
    builders:
      angular_components|scss_builder:
        enabled: True
```
Didn't help. So yes, please `Demonstrate how to use SASS to customize the layout`!
