### ISSUE TITLE
How do i get suggestions when typing for angular_components WebStorm

### ISSUE THREAD

**Issue by mranhtu** [dart-lang/angular_components#454]
How do i get suggestions when typing for angular_components WebStorm

WebStorm ver2019.3
<img width="338" alt="Screen Shot 2019-12-11 at 17 47 47" src="https://user-images.githubusercontent.com/58496039/70615485-10e23900-1c3f-11ea-90e7-ab7298298e25.png">

```
dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha
  intl: ^0.15.0
  google_maps: ^3.4.1
  skawa_components: ^1.2.1
  skawa_material_components: ^1.2.1
  sass_builder: ^2.1.2

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.6.0
```
